### PR TITLE
Fix build.config.id env, archive service rest api url, default local repository

### PR DESCRIPTION
**Pull request by yma955**

### CODE REVIEW

**Comment by yma955** [comment]
@ligangty @shokakucarrier, it seems that no access to add reviewer or merge to this codebase, please help to change the access and we need to fix some issues around.

**Comment by ligangty** [comment]
> @ligangty @shokakucarrier, it seems that no access to add reviewer or merge to this codebase, please help to change the access and we need to fix some issues around.

@yma88 Done and please have a check.

**Comment by yma955** [comment]
@ligangty it works, thanks!

**Comment by ligangty** [comment]
@yma88 I'm not quite aware of this repo. @shokakucarrier Can you help review this?

**Comment by shokakucarrier** [comment]
LGTM, some environment variable I wrote back then aren't fitting the standard, however I haven't run the script for quite a while, and don't have environment for it now, if you verified it I think we can merge this.

**Review by shokakucarrier — APPROVED** [review]
See comment above

**Pull request merged**
